# Configuration for CRAFTY Model

project_path: '' 

scenario: ''                              # Scenario identifier
regionalization: false						            # Only works if regional data is available (regional demands and GIS cell specificity).
# CRAFTY Mechanisms
initial_demand_supply_equilibrium: true       # Ensure balanced eco-service supply and demand during initial tick
remove_negative_marginal_utility: false       # Set marginal utility of production to 0 if negative
use_abandonment_threshold: true               # Abandon cell if agent competitiveness falls below threshold
mutate_on_competition_win: false              # Create new agent with mutations if competitor wins competition
mutation_interval: 0.01                       # Interval for mutation in child agent parameters
MostCompetitorAFTProbability: 0.8             # Probability of selecting the highest-utility AFT for cell
averaged_residual_demand_per_cell: false      # Averaged residual demand for each cell

# Neighboring Effects
use_neighbor_priority: true                   # Prioritize AFTs in neighboring cells for land competition
neighbor_priority_probability: 0.95           # Probability of selecting neighbor priority for competition
neighbor_radius: 2                            # Radius defining neighborhood if neighbor effect is enabled

# Competitiveness Process
land_abandonment_percentage: 0.03            # Percentage of land that can be abandoned per tick
participating_cells_percentage: 0.03          # Percentage of cells participating in competitiveness process
takeOverUnmanageCells_percentage: 0.8
marginal_utility_calculations_per_tick: 1     # Number of times the marginal utility calculated per tick

# ConsiderLandControle : true/false;
# List of landcontrole cosiderd  names    # all for all the mask will be considerd 
# landControle directory path example [urban ; C:\Users\byari-m\Desktop\CRAFTY_DATA\CRAFTY-EU-1km_upscaled_20.0\worlds\LandUseControl\Urban] 

# Output Configuration
generate_output_files: true                   # Enable CSV file output
output_folder_name: ''                        # If left empty defaults to timestamped folder,project_path\output\scenario\output_folder_name
generate_charts_plots_PNG: true
generate_charts_plots_PDF: false                     

generate_map_output_files: true
generate_map_plots_tif: false
map_output_frequency: 0                      # (Old version you can delete it and use map_output_years) Ticks interval for CSV output of land use and service supply
map_output_years: 5 #[2020,2025,2030,2040,2060,2100]      # Single integer N: export maps every N years; list [N1,...,Nm]: export maps for these exact years Ni
track_changes: true                         # Enable change tracking in output
export_LOGGER: true
LOGGER_info: true
LOGGER_warn: true
LOGGER_trace: false