name: JavaFX CI with Container

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    container:
      image: maven:3.8.4-openjdk-22

    steps:
    - uses: actions/checkout@v2

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
